### ISSUE TITLE
XA31: Differences between .rda and .dat

### ISSUE THREAD

**Issue by karl-koschutnig** [wtclarke/fsl_mrs#12]
Dear #wtclarke

We already had a quick chat this year regarding converting Siemens XA20 data to the Nifti format using your spec2nii tool. I really appreciated your help!!
Right now, we are acquiring SVS-data (now under XA 31) from a certain area in the hippocampus and want to use the fsl-mrs tool. Technically, I can convert our data and use the preproc script without any error messages. However, the spectra look very strange (compared to the spectra on the Siemens Console). So I thought that the problem might arise at the beginning of the preprocessing – the conversion. Attached you can find a plot of the same SVS-data: one was converted from .dat (resulting in one mtab file and one ref file), and the other was converted from .rda. 
It would be great if you could give me a hit on what the problem is. Thanks a lot!

By the way, the preproc script doesn’t work with the rda-converted data because of the missing Dimension tags ?!

Here are the mrs-infos from:
1)	Metab converted from .dat
NIfTI-MRS version 0.5
Data shape (1, 1, 1, 2080, 26, 200)
Dimension tags: ['DIM_COIL', 'DIM_DYN', None]
Spectrometer Frequency: 123.262808 MHz
Dwelltime (Bandwidth): 4.167E-04s (2400 Hz)
Nucleus: 1H
Field Strength: 2.90 T

2)	Wref converted from .dat
NIfTI-MRS version 0.5
Data shape (1, 1, 1, 2080, 26)
Dimension tags: ['DIM_COIL', 'DIM_DYN', None]
Spectrometer Frequency: 123.262808 MHz
Dwelltime (Bandwidth): 4.167E-04s (2400 Hz)
Nucleus: 1H
Field Strength: 2.90 T

3)	Metab converted from .rda
NIfTI-MRS version 0.5
Data shape (1, 1, 1, 1024)
Dimension tags: [None, None, None]
Spectrometer Frequency: 123.262808 MHz
Dwelltime (Bandwidth): 8.334E-04s (1200 Hz)
Nucleus: 1H
Field Strength: 2.90 T
![metab_XA31](https://user-images.githubusercontent.com/52704390/166743943-2ca6cba9-0c46-4086-8209-acf2328ffd97.jpg)

**Comment by wtclarke** [comment]
Hi @karl-koschutnig ,

Sorry for not responding to this back in May. I had a 2 day old daughter at the time so this completely slipped passed me at the time.

Clearly the rda conversion in spec2nii needs a bit of work. I only made a very basic implementation with the limited data I had at the time. Could you open an issue on the [@wtclarke/spec2nii ](https://github.com/wtclarke/spec2nii) repo and provide your example data if possible?

Regarding the odd looking data, what does it look like on the scanner? I.e. what do you expect? Are the dimensions here in the .dat file correct? I.e. a 20 ch coil and 200 averages

**Comment by wtclarke** [comment]
Hi @karl-koschutnig,

Looking more closely at this, the data out of the RDA and .dat files should be different. Much of the pre-processing is already applied (sometimes not appropriately) by the Siemens reconstruction routine, whilst the .data/twix data is unprocessed. The differences are correct and the RDA data doesn't need the full preprocessing (the failure could almost certainly print some better error messages though).

Regarding this data there are large residual water peaks which badly distort the baseline of the data. This probably needs to be fixed in acquisition.

I'll close this issue for now, but please do feel free to come back to me with more questions/issues.

Will

**Comment by karl-koschutnig** [comment]
Hello @wtclarke,
Tanks for your response and looking again at my dataset. I would have expected that Siemens does some magic tricks within their pipeline ;-)
We are also not happy with the data-quality. However, positioning a Voxel within the Hippocampus is challenging (at least for us).
Thanks again, 
Best, Karl

**Comment by wtclarke** [comment]
The hippocampus is challenging. I'd recommend making a thread on https://forum.mrshub.org/, there will be people on there with lots of useful tips / suggestions / experience of imaging the hippocampus.
