### ISSUE TITLE
dimension error in philips 3T MRS data reprocessing

### ISSUE THREAD

**Issue by karthikrrish** [wtclarke/fsl_mrs#18]
Hi,

I am relatively new to the field of MRS analysis. I am analyzing MRS data acquired for my Ph.D. 

I am running fsl_mrsproc with the following command :

`fsl_mrs_proc average --file /mnt/New_Volume/Karthik_Thesis/MRS_BS/Sub-250/sub-250.nii.gz/dACC_SVS_PRESS_35_ref.nii.gz --dim DIM_DYN --output fsl_mrs_proc --filename press_wref_tmp`

However, I get the following error : 

![image](https://user-images.githubusercontent.com/66436939/191184873-a8d64159-308d-489a-880f-7fa8561ac6f2.png)

Upon verifying, I found out that my data doesn't have the required parameter specified, as shown by the following command : 

![image](https://user-images.githubusercontent.com/66436939/191185204-b1d20d92-e34f-4ad9-8d89-a4bb3bdf96f7.png)

Help me make sense of this error. I have two doubts:
1. Is it a problem with the a) scan acquisition parameters; b) scanner software or c) spec2nii conversion that is responsible for the dimensions data not being shown?
2. Can I skip the steps which require the dimensions to be told to fsl_mrsproc?

**Comment by wtclarke** [comment]
Hi @karthikrrish,

Not all data needs all steps of the pre-processing to be run, as depending on the export pipeline from the scanner (e.g. raw data [.dat/.7/.SDAT/SPAR] vs. DICOM) different parts of the preprocessing has already been applied.

Here it looks like nearly all of the preprocessing has been applied by the scanner (this might not be optimal, but I don't know what data you have access to), so no need to repeat it in FSL.

I'd suggest you take a look at the Near et al pre-processing paper for more info. And drop by forums.mrshub.org for general help on MRS processing - there's a friendly crowd with lots of experience across scanners who can help guide you.
