### ISSUE TITLE
mrs_tools vis issues

### ISSUE THREAD

**Issue by laimab** [wtclarke/fsl_mrs#20]
We found an error in mrs_tools vis for MRSI data. When adding the --ppmlim subcommand, whether we specify a reasonable lower and upper limit, such as 0 6 or 4.2 4.5, or crazy values such as 0 100, the plot display is the same each time and it does not throw an error. We tested out mrs_tools vis with the SV Practical Data and it performs as expected (the --ppmlim subcommand works well).  Then tested mrs_tools vis with MRSI Practical Data and it does not perform as expected, it performs the same way also with our MRSI data (ignores or cannot handle the --ppmlim subcommand).

**Comment by wtclarke** [comment]
Hi @laimab , I believe this is now fixed in a recent version of https://github.com/wtclarke/nifti_mrs_tools (which now covers the `mrs_tools` functionality). Thanks for reporting the error.
