### ISSUE TITLE
DYM EDIT dimension

### ISSUE THREAD

**Issue by LuRoe7** [wtclarke/fsl_mrs#21]
Hi all,

I'm new to MRS analysis and to FSL-MRS in particular:

I've twix test data (SVS H-MRS of the hippocampus at 3T Siemens Prisma) that I converted to NIFTI (spec2nii twix). In contrast to the data used in the FSL practical, I've a DYM_EDIT dimension in the data.

Data is uploaded here: https://syncandshare.lrz.de/getlink/fiNFCp4Hfa9Dk5uGG7pDpi/

1. Now I was wondering how to deal with a DYM_EDIT as one dimension in the data? Is it appropriate to just average across DYM_EDIT with fsl_mrs_proc average?

2. Data looks pretty noisy to me, although three peaks are visible in the metabolite image (128 avgs). I briefly scanned the literature and saw a few published examples of Hippocampus-MRS that looked quite similar. Data of the anterior cingulate from the same subject at the same scanner during the same sequence looked much cleaner. I'd appreciate your opinion on that?

Best,

Lukas

**Comment by wtclarke** [comment]
Hi Lukas,

This is likely some ‘edited’ MRS data, i.e. a sequence like MEGA-PRESS. Does that ring any bells? Typically, you need to take the difference between the two elements as a (nearly) final step.

Hippocampal MRS is hard! I would always expect much lower signal in that region than cortical VOIs. Simply the tissue is much further from the receive coils, and you pay a significant SNR penalty for that. So this isn’t necessarily worrying, but you will need to figure out if you have sufficient signal for your experimental aims.

Will

From: Lukas Roell ***@***.***>
Date: Thursday, 13 April 2023 at 08:58
To: wtclarke/fsl_mrs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wtclarke/fsl_mrs] DYM EDIT dimension (Issue #21)

Hi all,

I'm new to MRS analysis and to FSL-MRS in particular:

I've twix test data (SVS H-MRS of the hippocampus at 3T Siemens Prisma) that I converted to NIFTI (spec2nii twix). In contrast to the data used in the FSL practical, I've a DYM_EDIT dimension in the data.

Data is uploaded here: https://syncandshare.lrz.de/getlink/fiNFCp4Hfa9Dk5uGG7pDpi/

  1.  Now I was wondering how to deal with a DYM_EDIT as one dimension in the data? Is it appropriate to just average across DYM_EDIT with fsl_mrs_proc average?
  2.  Data looks pretty noisy to me, although three peaks are visible in the metabolite image (128 avgs). I briefly scanned the literature and saw a few published examples of Hippocampus-MRS that looked quite similar. Data of the anterior cingulate from the same subject at the same scanner during the same sequence looked much cleaner. I'd appreciate your opinion on that?

Best,

Lukas

**Comment by LuRoe7** [comment]
Hi Will,

thank you the very quick reply and the explanations!

We acquired a MEGA-sLASER sequence. Do I need to take the difference between both elements here, too? Do you have any recommendations for guidelines, tutorials etc. that describe a valid analysis strategy for this kind of data?

Best,

Lukas

**Comment by wtclarke** [comment]
Hi @LuRoe7, Sorry for not getting back to you. Yes the process is the same for MEGA-sLASER. This paper is a useful start https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3825742/

**Comment by wtclarke** [comment]
Closing for now, feel free to ask for more help here or for general help with MRS, on the [MRSHub forum](https://forum.mrshub.org/)
