### ISSUE TITLE
GE P-Files

### ISSUE THREAD

**Issue by jharoon1** [wtclarke/fsl_mrs#23]
Dear FSL-MRS Developers,

Our team is hoping to use the FSL-MSR tools for the data processing for GE data. However, the spec2nii command seems to not recognize our p-file for conversion to nifti. Does anyone possibly know if there have been changes to p-files that have made them unable to be converted by spec2nii?

Thank you!

**Comment by wtclarke** [comment]
Hi @jharoon1,

I think this issue should be fixed in the new version of spec2nii released today `0.7.1`.

**Comment by wtclarke** [comment]
Closing this. Please let me know if it's still not fixed.
