### ISSUE TITLE
Create basis data with Vespa

### ISSUE THREAD

**Issue by lenn19** [wtclarke/fsl_mrs#7]
Hey,

do you know if there is a way to create basis spectra for FSL_MRS with the Vespa package? I already use it to create basis spectra for LCModel, so it would be quiet convenient to also use it for FSL_MRS basis spectra.

Thanks for your help

Lennard

**Comment by wtclarke** [comment]
Hi @lenn19,

I'm not very familiar with the VESPA basis set generation, but I think it should be possible. You have two choices, if you have an LCModel basis set that can be used, or you can manually create an FSL basis spectra set.

The FSL basis spectra are just JSON formatted files for each metabolite inside a single directory. Lots of simulation parameters are stored in that JSON file for the sake of provenance, but the only parameters actually required are quite limited.

If you take a look at one of the example files e.g.https://github.com/wtclarke/fsl_mrs/blob/master/example_usage/example_data/steam_11ms/Cr.json 
you will see that it has some nested arrays. The only ones which need filling in are:
```
      "basis": {  
		"basis_re": [.....], # Array of real part of the FID 
                "basis_im": [.....], # Array of imaginary part of the FID
		"basis_dwell": ..., # Dwell time in seconds
		"basis_centre": ..., # Central frequency in MHz
		"basis_width": ..., # Any broadening applied to the basis, in Hz
		"basis_name": "Cr" # Name matching the file name
                }
```
Hope that helps,

Will

**Comment by lenn19** [comment]
Hi @wtclarke,

you helped me a lot!

Thank you!
