### ISSUE TITLE
Show SVS voxel locations - notebook

### ISSUE THREAD

**Issue by lenn19** [wtclarke/fsl_mrs#8]
Dear FSL_MRS developers,

is there any way to show the SVS voxel locations in a T1-image when useing fsl_mrs in a notebook? At the reports and visualisation page I read that it would be easy to get the images with command line use. Unfortuanally i can't figure out how to show them with my notebook.

Thank you for your help!

**Comment by wtclarke** [comment]
Hi @lenn19 , apologies for the very long delay in answering. The T1 image with position is generated using the https://git.fmrib.ox.ac.uk/fsl/fsl_mrs/-/blob/master/fsl_mrs/utils/plotting.py#L1260 function.

**Comment by lenn19** [comment]
Hi @wtclarke, tanks for your answer. Cheers.
