### ISSUE TITLE
FSL MRS standard fitting model

### ISSUE THREAD

**Issue by lenn19** [wtclarke/fsl_mrs#9]
Hello,

I have a question regarding the paper **FSL-MRS: AN end-to-end spectroscopy analysis package**. In chapter 2.4.1 you mention the standard fitting model. In the first term M_l,g contains 𝜈;γg,𝜎g,𝜀g but in the second term M_l,g only contains 𝜈;𝛾 ,𝜀 although in the FFT 𝜎g is mentioned. Would you explain this to me?

Reguards

**Comment by wtclarke** [comment]
Hi @lenn19 This looks like the two available line shape models (lorentzian and voigt) have been muddled up in the equations. The first models the lineshapes as purely _Lorentzian_ , a function of a single parameter (γ), whilst the second models them as a mixture of _Lorentzian_ and _Gaussian_ functions, i.e. two parameters (γ and 𝜎). The model used is selectable on the command line.

**Comment by lenn19** [comment]
Thank you a lot!
